/**
 * Run a body of code in a throwaway script and get its value back.
 *
 * WHY THIS EXISTS. Bitburner charges a script for every ns.* name reachable
 * through its STATIC imports, called or not, and it bills by bare identifier -
 * so anything a long-lived script must not pay for has to live in a different
 * file. That constraint, not the logic, is what split this repo into twin
 * managers, twin preps, twin math backends and a calibration cache. A generated
 * script is invisible to that accounting: src/Script/RamCalculations.ts walks
 * only ImportDeclaration, so the body's cost is charged to the process that
 * runs it and never to the caller.
 *
 * The caller pays ns.run (1.00) and NOTHING else - write, read, getPortHandle,
 * nextPortWrite, clear and asleep are all 0 GB in this fork.
 *
 * ONE COPY, SHARED. scripts/continuous/ imports this directly rather than
 * carrying its own. That tree's self-containment rule exists to stop RAM
 * contamination, and a shared 1.00 GB module costs exactly what two copies
 * would.
 *
 * NOT for cheap or short-lived scripts. cloud.js, root.js, deploy.js and the
 * four gang/ transients already hold their RAM for under a second - routing
 * them through here saves nothing and adds 1.00 GB each. Never for the workers
 * (hack/grow/weaken/share): they are charged per thread and they ARE the call.
 *
 * Usage:
 *   import { rpc } from "./rpc.js";
 *   const c = await rpc(ns, `return { w: ns.weakenAnalyze(1) };`);
 *   const n = await rpc(ns, `return ns.getServerMaxMoney(args[0]);`, host);
 */

/**
 * Reply ports start here, and each CALLER gets RPC_PORT_BASE + its own pid.
 *
 * Ports 1-4 are taken (shotgun reports, share gate, continuous reports, gang),
 * and a single shared reply port would let two resident callers read each
 * other's answers - a wrong number, silently, which is the worst failure class
 * in this repo. Any positive integer is a legal port: CONSTANTS.NumNetscriptPorts
 * is Number.MAX_SAFE_INTEGER, so keying by pid costs nothing and cannot collide.
 */
export const RPC_PORT_BASE = 1000;

/**
 * A transient that dies before writing would otherwise hang nextWrite() for
 * good - killall, a ScriptDeath, or the game reloading mid-call.
 */
export const RPC_TIMEOUT_MS = 10000;

/**
 * ponytail: regex, not a parser - there is no package.json here by design, so
 * no acorn to walk with. A body's imports have to be hoisted because `import`
 * is only legal at module scope, and the body runs inside main(). Known
 * ceiling: only single-line imports are matched. Write them on one line, which
 * is how every import in this repo is already written.
 */
const IMPORT_LINE = /^[ \t]*import[ \t][^\n]*$/gm;

/** One rpc in flight per process - see the guard in rpc(). */
let busy = false;

/** djb2, so an identical body always lands on an identical filename. */
function digest(text) {
  let n = 5381;
  for (let i = 0; i < text.length; i++) n = (((n << 5) + n) ^ text.charCodeAt(i)) >>> 0;
  return n.toString(36);
}

/**
 * Wrap a body into a runnable module.
 *
 * The reply port arrives as ARGUMENT ZERO rather than being baked into the
 * source. Baking it in would make the text depend on the caller's pid, so every
 * restart would mint a new filename and the litter would grow without bound.
 * As written, the same body is always the same bytes - and Script.ts:39 returns
 * early from `set content` when the code is unchanged, so rewriting it neither
 * invalidates the module nor re-prices it.
 *
 * The body's own throw is caught HERE, inside the transient, and returned as a
 * value. A transient that dies takes its log window with it a few hundred ms
 * later, so an uncaught error would reach the caller as a timeout naming
 * nothing - the same trap gang/report.js exists to close.
 */
export function source(body) {
  const hoisted = body.match(IMPORT_LINE) ?? [];
  const rest = body.replace(IMPORT_LINE, "");
  return `${hoisted.join("\n")}
/** Generated by scripts/rpc.js. Rewritten whenever the body changes; safe to delete. */
export async function main(ns) {
  const [back, ...args] = ns.args;
  let out;
  try {
    out = { v: await (async () => {${rest}
    })() };
  } catch (err) {
    out = { e: String((err && err.message) || err) };
  }
  ns.writePort(back, JSON.stringify(out));
}
`;
}

/**
 * @param {NS} ns
 * @param {string} body statements of a function receiving `ns` and `args`
 * @param {...(string|number|boolean)} args passed through as `args` in the body
 * @returns {Promise<any>} whatever the body returned, via JSON
 */
export async function rpc(ns, body, ...args) {
  // Concurrent calls from one process would share a reply port and swap
  // answers. The game's own concurrency check does not catch this, because
  // nextWrite() is not a blocking netscript call - so the guard has to be here.
  if (busy) throw new Error("rpc: a call is already in flight - await each one");
  busy = true;
  try {
    const file = `/tmp/rpc-${digest(body)}.js`;
    ns.write(file, source(body), "w");

    const back = RPC_PORT_BASE + ns.pid;
    const handle = ns.getPortHandle(back);
    // A previous call that timed out may still land. Dropping it here is what
    // stops a late reply being read as this call's answer.
    handle.clear();

    const pid = ns.run(file, { threads: 1, temporary: true }, back, ...args);
    // ns.run returns a bare 0 for BOTH "no free RAM on home" and "the file does
    // not compile", and says nothing. Naming the file is the only way the next
    // log diagnoses itself rather than costing a round trip.
    if (pid === 0) {
      throw new Error(`rpc: ns.run returned 0 for ${file} - no free RAM on home, or the body does not compile`);
    }

    await Promise.race([handle.nextWrite(), ns.asleep(RPC_TIMEOUT_MS)]);
    if (handle.empty()) {
      throw new Error(`rpc: ${file} (pid ${pid}) wrote nothing within ${RPC_TIMEOUT_MS}ms`);
    }

    const out = JSON.parse(handle.read());
    if (out.e !== undefined) throw new Error(`rpc: ${file} threw: ${out.e}`);
    return out.v;
  } finally {
    busy = false;
  }
}
